# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family FiraCode Nerd Font
font_size 16.0

macos_thicken_font 1

#: }}}

#: Window {{{

enabled_layouts tall:bias=50;full_size=1;mirrored=true,stack

background_opacity 0.95
background_blur 10

update_check_interval 0

strip_trailing_spaces smart

#: }}}

#: macOS {{{

macos_show_window_title_in none
macos_titlebar_color #1A1B26
macos_menubar_title_max_length 0

#: }}}

#: Keyboard maps {{{

# Scrollback
map cmd+f launch --type=overlay --stdin-source=@screen_scrollback nvim -c 'set nobackup nowritebackup' -c 'set buftype=nofile' -c 'set wrap' -c 'normal G'

# Layout actions (tall)
map ctrl+[ layout_action decrease_num_full_size_windows
map ctrl+] layout_action increase_num_full_size_windows
map ctrl+/ layout_action mirror toggle
map ctrl+. layout_action bias 50 62 70
map ctrl+, layout_action bias 62

# Window navigation (vim: ctrl+w hjkl)
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

# Move window (vim: ctrl+w HJKL)
map ctrl+shift+h move_window left
map ctrl+shift+l move_window right
map ctrl+shift+j move_window down
map ctrl+shift+k move_window up

# Window operations
map cmd+enter   launch --cwd=current
map ctrl+enter  toggle_layout stack
map cmd+w       close_window_with_confirmation
map shift+cmd+d close_window_with_confirmation

# Tabs
map cmd+shift+. next_tab
map cmd+shift+, previous_tab

#: }}}

#: Theme {{{

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

#: }}}
